### PR TITLE
[W-4288462] Display version info correctly in Azkaban

### PR DESCRIPTION
**Pull request by jiohyoo**
- read version.properties and show version in header, and version details in /index page
- the version.properties will be provided by PR https://github.com/relateiq/docker-azkaban-solo/pull/196

image

### CODE REVIEW

**Comment by dszeto** [comment]
Hey @jiohyoo , it looks like we are removing a standard Azkaban feature (label) here. Can we change the presentation a bit so that we have an extra version string attached, and preserve the labelling capability? Labelling is still supported upstream and it is also probably used by RIQ.

**Comment by jiohyoo** [comment]
pushed the change so that it shows the version info after the azkaban label @dszeto

**Comment by dszeto** [comment]
What are those `only for testing` changes? Should they be reverted or merged?

**Comment by jiohyoo** [comment]
pushing with changed version so that docker-solo can pick it up when deployed from TC. will revert

**Pull request merged**
