### PR TITLE
Batching execution update calls

### PR DESCRIPTION
**Pull request by yanyang82**
Bumped both maxContentFormSize and headerBufferSize in both executor/web server Jetty, and still hitting 143. 

This PR batches the execution update calls into batches of 100s so each HTTP call will not have a header too big to fit.

### CODE REVIEW

**Comment by einstein-mychen** [comment]
LGTM; we should batch more in case batch of 100s is not enough

**Comment by einstein-mychen** [comment]
@yanyang82 please change gradle version to 42 for resolving conflicts

**Comment by ajmssc** [comment]
Let teamcity manage the version plz

**Comment by einstein-mychen** [comment]
get rid of the version change; ready to merge

**Pull request merged**
