### PR TITLE
Auto Refresh of Job View

### PR DESCRIPTION
**Pull request by hjdesai2**
Auto Refresh of Job View

### CODE REVIEW

**Comment by hjdesai2** [comment]
@yevgenius @ajmssc If 5 Seconds is too Fast, then I can increase to 15 or 30 Seconds..

**Comment by atbida** [comment]
@hjdesai2 are you adding the View refresh and removing the Model Refresh?

**Comment by hjdesai2** [comment]
@atbida yes !!!

**Comment by ajmssc** [comment]
@hjdesai2 you tested this and it works?
If yes then LGTM.

Note: You will have to manually copy the js file to https://github.com/relateiq/docker-azkaban-solo/tree/master/solo/web/js because the docker uses these files instead of the ones in the jar

**Comment by hjdesai2** [comment]
@ajmssc yeah It works :)

**Pull request merged**
